; Plantilla MAESTRA multi-entorno.
; Compila los tres con: pio run
; Compila uno solo con:  pio run -e uno
;
; RECORDATORIO IntelliSense: compile_commands.json es POR ENTORNO.
; Al cambiar de entorno regenera con: pio run -e <env> -t compiledb
; Si no, clangd muestra errores fantasma con includes del toolchain anterior.

[platformio]
default_envs = uno

[env]
framework = arduino
monitor_speed = 115200
monitor_filters = time, colorize, send_on_enter

[env:uno]
platform = atmelavr
board = uno

[env:esp32dev]
platform = espressif32
board = esp32dev
monitor_filters = esp32_exception_decoder, time, colorize, send_on_enter
upload_speed = 921600

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
monitor_filters = esp32_exception_decoder, time, colorize, send_on_enter
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
