; Arduino Uno R3 (ATmega328P) - toolchain atmelavr
; Verificado end-to-end: COM9, CDC nativo, sin driver externo.
[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
monitor_filters = time, colorize, send_on_enter
build_flags = -Wall
; upload_port = COM9   ; NO lo fijes: PlatformIO autodetecta. Solo descomenta
;                        si tienes VARIAS placas conectadas a la vez.
