; ESP32-S3 DevKitC-1 - USB-JTAG nativo (303A:1002), sin driver externo
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize, send_on_enter
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
debug_tool = esp-builtin
