; ESP32 clasico (WROOM-32) - toolchain espressif32 / Xtensa
; Chip USB-serie tipico: CP2102 (10C4:EA60) o CH9102 (1A86:55D4).
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize, send_on_enter
upload_speed = 921600
build_flags =
    -DCORE_DEBUG_LEVEL=3
lib_deps =
;   ejemplo: bblanchon/ArduinoJson@^7.0.0
