; Wemos D1 mini (ESP8266) - chip CH340 (1A86:7523) en la mayoria de clones
[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder, time, colorize, send_on_enter
upload_speed = 921600
board_build.filesystem = littlefs
