; Arduino Nano - dos variantes de bootloader
; Si el upload falla con "programmer is not responding", prueba la otra.
[env:nano_new]
platform = atmelavr
board = nanoatmega328new   ; bootloader nuevo (115200 baud)
framework = arduino
monitor_speed = 115200
monitor_filters = time, colorize, send_on_enter

[env:nano_old]
platform = atmelavr
board = nanoatmega328      ; bootloader viejo (57600 baud)
framework = arduino
monitor_speed = 115200
monitor_filters = time, colorize, send_on_enter
