; ESP32-C6 / C5 / H2 / P4 con Arduino Core 3.x
; El platform oficial espressif32 NO alcanza para estos chips.
; Se usa el fork pioarduino, que si trae el core 3.x.
[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time, colorize, send_on_enter
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
debug_tool = esp-builtin
